spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      database: mongodb_tutorial
      username: root
      password: root

server:
  port: 8080